owner: Pedro21062014
repo: Crm-status

sites:
  - name: NovaCRM
    url: https://novacrm.com.br
    expectedStatusCodes:
      - 200

status-website:
  cname: status.novacrm.com.br
  baseUrl: ""
  name: NovaCRM Status
  introTitle: "Status da Plataforma NovaCRM"
  introMessage: "Monitoramento em tempo real"
  logoUrl: https://raw.githubusercontent.com/Pedro21062014/nova-crm-desktop/refs/heads/main/build/icon.png
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/Pedro21062014/Crm-status
